### PR TITLE
 set flags and attrs for fsetstat packet type in filecmd

### PR DESCRIPTION
**Pull request by sigmonsays**

### CODE REVIEW

**Comment by sigmonsays** [comment]
sounds good, i'll make the change shortly.

**Comment by sigmonsays** [comment]
So on second thought.. there is an issue with this approach because *sshFxpFsetstatPacket does not have a path, and that's how pkt is typed. I wasn't sure changing the signature of that function (requestFromPacket) was correct. Should I make a new type which combines both hasPath and hasHandle ?

**Comment by eikenb** [comment]
Hold on.. let me take another look at that code. I thought I had Fsetstat working like Setstat, but I may be mis-remembering.

**Comment by eikenb** [comment]
Sorry, you were correct. The requestFromPacket() method doesn't even get called for an sshFxpFsetstatPacket packet. The Request object gets created when the initial sshFxpOpenPacket is processed, so the incoming sshFxpFsetstatPacket would find the existing handle/Request and use it.

Unfortunately there doesn't seem like there is a better place for it. I had hoped to have the request object all situated by that point in the code, but there is just no place in the code obviously better than in your original fix. I'm thinking I should just merge it for now and maybe something will come to me during a later refactor.

**Comment by sigmonsays** [comment]
Thanks. As I spend more time in the code perhaps i'll be able to help come up with a better solution as well.

**Comment by eikenb** [comment]
Sigh. I pulled it down and rebased/merged it locally and push. I thought that would close this out but it seems my rebase screwed that up. But it is merged and you got credit.

**Comment by eikenb** [comment]
Forgot to say thanks. I appreciate your looking into and fixing this... addressed not only your issue but one other. Been super lacking on time recently and it is a big help.

**Pull request closed without merging**
