### PR TITLE
data packet unmarshal binary: remove uneeded copy

### PR DESCRIPTION
**Pull request by drakkan**

### CODE REVIEW

**Comment by drakkan** [comment]
some interesting numbers here:

https://github.com/drakkan/sftpgo/issues/69#issuecomment-587638120

this patch give a 20% performance improvement for the user who posted the results. In my tests, on my laptop, the improvement is smaller

**Comment by drakkan** [comment]
@puellanivis  Thanks!

I wonder if we can improve this code too:

```
       bb, err := m.MarshalBinary()
       ...
        // Slide packet down 4 bytes to make room for length header.
        packet := append(bb, make([]byte, 4)...) // optimistically assume bb has capacity
        copy(packet[4:], bb)
```

I need to find some time to benchmark the different ways to prepend `packet` (fixed 4 bytes) to bb that could be bigger. 

For what I can see reading pkg/sftp code there are no other obvious optimizations

**Comment by puellanivis** [comment]
prepending is known to be an expensive operation, which is why Go does not have a builtin primitive for it, that would parallel `append`.

Although, looking at it, it might be better to just allocate the 4 bytes at the head right from the start, and just skip over them. Then later we can inject the length into it.

**Comment by drakkan** [comment]
the latest patch, applied on the top of my allocator branch, make pkg/sftp write performance very similar to my scp implementation

**Comment by eikenb** [comment]
Travis has made it impossible to trigger re-tests so I'll pull this down and check locally. The integration tests can be a bit overly fragile.

**Comment by eikenb** [comment]
I triggered 2 travis runs and they both came back fine. So just going to ignore the failure and merge this.

**Comment by eikenb** [comment]
@drakkan Thanks for the PR!
@puellanivis Thanks for the review!

**Pull request merged**
