### PR TITLE
sftp: ensure all tests pass on windows (except for integration tests)

### PR DESCRIPTION
**Pull request by kardianos**
All tests now pass on windows except for the integration tests which have deep unix assumptions.

Builds on https://github.com/pkg/sftp/pull/159 . Is this the best way to send a patch series on git?

### CODE REVIEW

**Comment by eikenb** [comment]
To fix #157 I went ahead and implemented the linux version + stub version of the fakeFileInfoSys() method. I put them in a different file keeping in line with the naming convention of the other os-dependent files. This will obviously affect this PR, but I will address that along with a few changes I'd like to see in a later comment. My priority is to first get the basic builds working again on windows (which I broke).

**Comment by eikenb** [comment]
I'd like the files to be named a bit more consistently with the way the other platform dependent files. That is something related to what they are for, like the attrs_unix.go for attrs.go. For the fakeFileInfoSys() methods I went with request-unix.go and request-stub.go to associate them with the rest of the request code.

Could you please use this naming schemes for the other files..
- os_unix.go -> request-unix.go (already done)
- os_unix_test.go -> request-server-unix_test.go
- os_windows.go -> request-server-windows_test.go
- os_windows_test.go -> request-server-windows_test.go

Also the +build flags need to be fleshed out a bit. You are missing flags on the windows specific files and the unix files should be more in line with the other in use. See server_unix.go, server_stub.go and the other build flags for examples.

Thanks for all your work. As I don't presently have access to a Windows system for testing, I'm dependent on people such as yourself and I appreciate your time.

**Comment by kardianos** [comment]
The convention in go is to use underscore rather then hyphens for file names. However we can do "request-server_windows_test.go". This will tell the go compiler that this is a windows only file and a test file all at once, no build tag required.

If you'd like me to list out all the non-windows platforms I can do so, but I thought it was simpler just to say `//+build !windows` which should be equivalent.

Thanks for taking a look. I'll look into and adjust soon.

**Comment by eikenb** [comment]
> However we can do "request-server_windows_test.go". This will tell the go compiler that this is a windows only file and a test file all at once, no build tag required.

That's great. I didn't know about the _os magic file naming. Reading about it now. Thanks. 

My rule of thumb is dashes for names that were just names (carried no meaning to the builder) and underscores for  semantic names (was just _test). This makes the OS bit meaningful so please do change my request to be in line with what you suggested.

I'll have to think about how this affects the build flags. Dave seemed pretty explicit with them and I was continuing with that as I haven't done a lot of work cross platform (non-unix). You can probably leave your tags alone in this case, as I'm going to review all build flags after studying up on them more.

Thanks again.

**Comment by hferentschik** [comment]
Hi, I am trying to compile HEAD of pkg/sftp for Windows and I am getting:

    vendor/github.com/pkg/sftp/request-example.go:190: undefined: syscall.Stat_t

I figure this is somehow related to this pull request, right? I am also wondering whether sftp server is working on Windows? Or are we just talking about ways to cross compile on Windows for Darwin/Linux? I am after an sftp server which works on all OS types. Is this the case? Thanks for your help.

**Comment by eikenb** [comment]
@hferentschik This was reported as issue #157 and I pushed a fix 3 days ago. Please check that you are up to date.

**Comment by hferentschik** [comment]
> This was reported as issue #157 and I pushed a fix 3 days ago. Please check that you are up to date.

Right, I had an other dependency which tried to include sftp in an earlier version. I switched now to
94df0a367c78a139a5351d2a3ec204b61170ded9. However, now I get:

     vendor/github.com/pkg/sftp/request-stub.go:8: undefined: syscall.Stat_t

And that seems to be aligned with what I see in master https://github.com/pkg/sftp/blob/master/request-stub.go#L8.

**Comment by eikenb** [comment]
I missed the change in my commit. Just pushed it. Thanks for catching and reporting that.

**Comment by hferentschik** [comment]
> Thanks for catching and reporting that.

no worries

**Comment by kardianos** [comment]
@eikenb I don't mean to be picky, but I'm not sure I would expect `syscall.Win32FileAttributeData{}` to be present on android, as is implied with the build tag. I also don't see what this has to do with cgo.

You'd be better off just calling the request-stub_windows.go and removing the build tag altogether.

**Comment by eikenb** [comment]
@kardianos No please, be picky. This is the first project I've helped out with that supports non-*nix platforms and am being a bit slow about it. I just copied and pasted that from one of the other files that was for windows, and didn't review the tags properly.

So I probably need to fix the tags in that file and add a purely stub one that just returns and empty interface for android.

**Comment by kardianos** [comment]
@eikenb I'm confused by the various changes I'm seeing in this code base.

I can update this pull request if you want, but what is your plan?

**Comment by eikenb** [comment]
@kardianos My short term plan is to fix the remaining major issues, try to get windows in a usable state and then tag a release. I'm still getting a feel for multi-platform support and so some of my commits related to that have been around trying to settle on the best way to do things. Hope that helps explain what I'm doing a bit, if you have more specific questions please ask.

If you'd like to update the pull request, I'd be happy to review it for inclusion. It would be a big help towards getting it usable on windows.

**Comment by eikenb** [comment]
I believe merged PR #191 addressed this issue.

**Pull request closed without merging**
