### PR TITLE
Bug with sub folders/files of a renamed/removed path

### PR DESCRIPTION
**Pull request by danfletcher1**
When removing or renaming a folder, sub files/folders of the path were not being updated. I just created a loop to update anything with a matching path.

### CODE REVIEW

**Comment by eikenb** [comment]
Hey @danfletcher1, thanks for the patch. 

Looks good though I'm not sure about the remove behavior. Most SFTP servers (and most filesystems) won't delete a directory when it has content and I think that is more correct. It should return an error when trying to remove a directory that still has content.

It doesn't do that either... if you'd like to change remove to return an error, otherwise just remove that part. I'd have it return an os.PathError type... mimicing os.Remove()'s behaviour.

**Comment by danfletcher1** [comment]
Thanks for the advice. I will change that.

Kind regards
Dan

**Comment by danfletcher1** [comment]
Applied your advice.

**Comment by eikenb** [comment]
Looks good. Thanks for the changes.

**Pull request merged**
