### PR TITLE
Export RealPath for potential client use

### PR DESCRIPTION
**Pull request by puellanivis**
Real simple, it’s exactly what the title says, nothing more.

### CODE REVIEW

**Comment by puellanivis** [comment]
As mentioned I went through the path handling code. It’s all generally server-side stuff. Nothing necessary to be done on the client side.

The standard even says this request packet can be called with essentially any arbitrary path.

**Comment by drakkan** [comment]
Great! I suggest to add a comment to avoid warnings like this one `exported method Client.RealPath should have comment or be unexported`.

**Comment by drakkan** [comment]
server side the method just calls [cleanPacketPath](https://github.com/pkg/sftp/blob/master/request-server.go#L266) so specific test cases should not be needed

**Comment by puellanivis** [comment]
Feel free to merge, and then cut a release at your leisure.

**Pull request merged**
